#
# CD build that makes releases from the main dev branch.
#
# - skipping release: add [skip release] to the commit message
#
name: CI

on:
  push:
    branches: [main]
    tags-ignore: [v*]

jobs:
  gradle_wrapper_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0" # https://github.com/shipkit/shipkit-auto-version#fetch-depth-on-ci
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1.0.5

  deploy:
    runs-on: ubuntu-latest
    # We run Windows build first because we will be publishing artifacts from the Ubuntu build (simplifies workflow)
    needs: [gradle_wrapper_validation]
    if: "! contains(toJSON(github.event.commits.*.message), '[skip release]')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0" # https://github.com/shipkit/shipkit-auto-version#fetch-depth-on-ci
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 16
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Perform Build via Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --continue --scan
      - name: Publish Plugin and Create GitHub Release via Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishPlugins githubRelease --scan
        env:
          # Gradle env variables docs: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
